### ISSUE TITLE
Global stopwatch functions

### ISSUE THREAD

**Issue by hexmar** [hexmar/website#1]
### Tasks
- [ ] Save state to local storage
- [ ] Add divider at another day
- [ ] Add description
- [ ] Export state
- [ ] Import state
- [ ] Change time/description
- [ ] Remove moment
- [ ] Location at moment
- [ ] Add colors
- [ ] Type of moment (on foot, by car, ...)
- [ ] Multiple lists
